/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jvfx2;

import java.awt.Button;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {

 
    public static void main(String[] args) {
    	launch(args);
      
    }

	@Override
	public void start(Stage primaryStage) throws Exception {
	primaryStage.setTitle("Esse é o meu Palco");
    Button button = new Button();
     button.setText("my button");
     StackPane stackPane = new StackPane();
     primaryStage.setScene(new Scene (stackPane,800,600));
     primaryStage.show();
	}
}
