/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jvfx2;


import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class App extends Application {

 
    public static void main(String[] args) {
    	launch(args);
      
    }

	@Override
	public void start(Stage primaryStage) throws Exception {
	primaryStage.setTitle("Esse é o meu Palco");
	VBox vbox = new VBox();
	
	Text usernameLabel = new Text();
    usernameLabel.setText("Username:");
    vbox.getChildren().add(usernameLabel);
	
  
	TextField userField = new TextField();
	userField.setText("");
	vbox.getChildren().add(userField);
	
	Text passowordLabel = new Text();
	passowordLabel.setText("Senha:");
	vbox.getChildren().add(passowordLabel);
	
	TextField senhaField = new TextField();
	senhaField.setText ("");
	vbox.getChildren().add(senhaField);
   
	 Button button = new Button();
    button.setText("ENTRAR");
    
    
    vbox.getChildren().add(button);
    
    primaryStage.setScene(new  Scene(vbox,800,600));
    primaryStage.show();
 
	}
}
